FROM node:16
WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps
COPY . .
RUN npm run build
EXPOSE 3000/tcp
# ENV Jwt__SecretKey=$Jwt__SecretKey
# ENTRYPOINT ["dotnet", "Payment.Api.dll"]
CMD [ "npm", "start" ]