FROM node:16-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
RUN npm run generate
EXPOSE 3000/tcp
# ENV Jwt__SecretKey=$Jwt__SecretKey
# ENTRYPOINT ["dotnet", "Payment.Api.dll"]
CMD [ "npm", "start" ]