version: '3.9'
services:
  migrate:
    image: 'node:16-alpine'
    env_file:
      - /root/hsapdev/.env
    depends_on:
      - db
    restart: 'no'
    volumes:
      - ./prisma:/prisma
    # command: sh -c "npx --yes prisma migrate deploy"
    command: sh -c "npx --yes prisma migrate resolve --applied 20220820223423_init"
    profiles: ['migrate']

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:4000'
    depends_on:
      - db
      - redis
    restart: always
    env_file:
      - /root/hsapdev/.env

  db:
    image: 'mysql:8.0.29'
    env_file:
      - /root/hsapdev/.env
    ports: ['3306:3306']
    # environment:
    #   MYSQL_DATABASE: hairsap_dev
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #   MYSQL_USER: ${MYSQL_USER}
    #   MYSQL_PASSWORD: ${MYSQL_USER}
    restart: always
    container_name: mysql_hsap_db
    volumes:
      - /root/hsapdev/mysql_data:/var/lib/mysql

  redis:
    image: 'redis:7.0.4-alpine3.16'
    restart: always
    command: sh -c "exec redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - /root/hsapdev/.env
    # environment:
    #   REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: redis_hsap_db
    volumes:
      - '/root/hsapdev/redis_data:/data'
