version: '3.9'
services:
  backend:
    build:
      context: .
      #  args:
      #   - VITE_BASE_URL=https://pay-back.babajideadedeji.com/api/v1
    command: npm run dev
    ports:
      - '5000:3000'
    # depends_on:
    #   - db
    #   - redis
    restart: always
    # user: '1000:1000'
    # env_file:
    #   - .env
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      JWT_ADMIN_SECRET: ${JWT_ADMIN_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      PORT: 5000
    volumes:
      - '.:/app'
      - '/app/node_modules'
    tty: true

  db:
    image: 'mysql:8.0.29'
    environment:
      MYSQL_DATABASE: hairsap_dev
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER}
    restart: always
    container_name: mysql_hsap_db
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis:
    image: 'redis:7.0.4-alpine3.16'
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: redis_hsap_db
    volumes:
      - './redis_data:/data'
