[environments.production.build]
dockerfilePath = "Dockerfile.prod"

[environments.production.deploy]
startCommand = "npm run mig:start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5