[environments.production.build]
dockerfilePath = "Dockerfile.prod"

[environments.production.deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5