@base = http://localhost:4000
@stag = https://staging.hairsap.com
@prod = https://hairsap-be-production.up.railway.app
@otp= "{{loginUser.response.body.data.otp}}"
@utoken= {{loginUser.response.body.data.token}}
@atoken= {{loginAdmin.response.body.data.token}}
@ptoken= {{loginPro.response.body.data.token}}
@userid= {{loginUser.response.body.data.user.userId}}


###
GET {{base}} HTTP/1.1

###
POST {{base}}/auth/signup HTTP/1.1
Content-Type: application/json

{
    "email":"lodashed@gmail.com",
    "password":"jide1234",
    "name":"Jide Adedeji",
    "phone":"+2348118161239",
    "role":"user",
    "otpType":"email"
}

###
POST {{prod}}/auth/signup HTTP/1.1
Content-Type: application/json

{
    "email":"jideadedejifirst@gmail.com",
    "password":"jide1234",
    "name":"Jide Adedeji",
    "phone":"+2348118161239",
    "role":"user",
    "otpType":"email"
}

###
# @name loginUser
POST {{prod}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"jideadedejifirst@gmail.com",
    "password":"jide1234",
    "role":"user"
}

###
# @name loginPro
POST {{base}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"jamesadedejifirst@gmail.com",
    "password":"jide1234",
    "role":"pro"
}
###
# @name loginAdmin
POST {{base}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"jide1234",
    "role":"admin"
}
###
# @name loginAdmin
POST {{stag}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"",
    "role":"admin"
}

###
# @name generateOtp
POST {{prod}}/auth/generateotp HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

{
    "userId": 3,
    "otpType":"email"
}

###
# @name validateOtp
POST {{base}}/auth/validateotp HTTP/1.1
Content-Type: application/json

{
    "userId": {{userid}},
    "otp": {{otp}},
    "role":"user"
}

###
# @name validateOtp
POST {{prod}}/auth/validateotp HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

{
    "userId": 3,
    "otp": "298830"
}

###
PATCH {{base}}/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

{
    "photoUrl":"http"
}

###
PATCH {{base}}/pros HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ptoken}}

{
    "userId":3,
    "address":"updated address"
}

###
GET {{base}}/chats HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

###
POST {{base}}/chats HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
    "userId": 2,
    "take":3,
    "desc":true
}

###
POST {{base}}/chats HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{}}

{
    "userId": 2,
    "take":3,
    "desc":true,
    "cursor":9
}

###
GET {{base}}/chats/2?cursor=&take=2&desc=true HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

###
POST {{base}}/pros/auto HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

{
    "latitude":6.520238459241921,
    "longitude":3.3680734868226345,
    "subServiceId":1
}

###
POST {{base}}/admin/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{atoken}}

{
    "serviceId":2
}

###uto
POST {{stag}}/admin/userbookings HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{atoken}}

{
    "userId":2
}

###
POST {{base}}/admin/userbookings HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

{
    "userId":1
}

###
POST {{base}}/pros/auto HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

{
    "subServiceId":1,
    "latitude":10,
    "longitude":10,
    "userId":3,
    "distance":825544.0818356347
}

###
GET {{base}}/bookings/transactions HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

###
GET {{base}}/users/subscriptions HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

###
POST {{base}}/users/subscribe HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

{
    "proId":3
}

###
GET {{base}}/admin/dashboard HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{atoken}}

###
POST {{base}}/admin/dashboard/bookings HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{atoken}}

{
    "limit":"all",
    "period":"month",
    "status":"all"
}

###
POST {{base}}/admin/dashboard/bookings/discounted HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{atoken}}

###
POST {{base}}/admin/dashboard/bookings/completed HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{atoken}}


###
POST {{base}}/admin/probookings HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{atoken}}

{
    "proId":3,
    "status":"returned",
    "period":"month"
}

###
GET {{base}}/admin/pros/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{atoken}}
###
GET {{base}}/pros/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

###
POST {{base}}/admin/pros HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{atoken}}

###
GET {{base}}/pros/booking/ratio/3/week HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ptoken}}

###
POST {{base}}/bookings HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

{

}

###
POST {{base}}/auth/signup HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

{
    "role":"pro",
    "serviceId":1,
    "email":"jideadedejifirst@gmail.com",
    "name":"pro 10",
    "password":"jide1234",
    "phone":"08118161237",
    "address":"no 10",
    "businessName":"Jide services"
}

###
POST {{base}}/deactivate HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

{
    "role":"pro",
    "serviceId":1,
    "email":"jideadedejifirst@gmail.com",
    "name":"pro 10",
    "password":"jide1234",
    "phone":"08118161237",
    "address":"no 10",
    "businessName":"Jide services"
}

###
POST {{base}}/deactivate HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ptoken}}

{
 
}

###
POST {{base}}/auth/changepassword HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

{
 "newPassword":"jide1234",
 "oldPassword":"jide12345"
}


###
GET {{base}}/services HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

###
GET {{base}}/pros/stats/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ptoken}}

###
GET {{base}}/marketer/stats HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{atoken}}

###
GET {{base}}/bookings/2/activity HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

###
POST {{base}}/pushtoken/jidee HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}

###
POST {{base}}/users/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{utoken}}


